disable macos/arm build, e2e test and release in main_build to speed up debug

diff --git a/.github/workflows/main_build.yml b/.github/workflows/main_build.yml
--- a/.github/workflows/main_build.yml
+++ b/.github/workflows/main_build.yml
@@ -21,7 +21,7 @@ jobs:
       matrix:
         include:
           - os: windows-latest
-          - os: macos-latest
+          # - os: macos-latest
           - os: ubuntu-latest
 
     steps:
@@ -77,27 +77,27 @@ jobs:
           name: aws-distro-opentelemetry-dotnet-instrumentation-macOS
           path: bin/aws-distro-opentelemetry-dotnet-instrumentation-macos.zip
   
-  build-arm:
-    runs-on: codebuild-adot-dotnet-runner-${{ github.run_id }}-${{ github.run_attempt }}
-    steps:
-      - uses: actions/checkout@v3
+  # build-arm:
+  #   runs-on: codebuild-adot-dotnet-runner-${{ github.run_id }}-${{ github.run_attempt }}
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Setup .NET
-        uses: actions/setup-dotnet@v2
-        with:
-          dotnet-version: '8.0.x'
+  #     - name: Setup .NET
+  #       uses: actions/setup-dotnet@v2
+  #       with:
+  #         dotnet-version: '8.0.x'
 
-      - name: Build on Linux
-        run: bash build.sh
+  #     - name: Build on Linux
+  #       run: bash build.sh
 
-      - name: Test on Linux
-        run: dotnet test
+  #     - name: Test on Linux
+  #       run: dotnet test
 
-      - name: Upload Artifact on ARM Linux
-        uses: actions/upload-artifact@v3
-        with:
-          name: aws-distro-opentelemetry-dotnet-instrumentation-linux-arm64
-          path: bin/aws-distro-opentelemetry-dotnet-instrumentation-linux-glibc-arm64.zip
+  #     - name: Upload Artifact on ARM Linux
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: aws-distro-opentelemetry-dotnet-instrumentation-linux-arm64
+  #         path: bin/aws-distro-opentelemetry-dotnet-instrumentation-linux-glibc-arm64.zip
   
   build-x64-musl:
     runs-on: ubuntu-latest
@@ -120,158 +120,158 @@ jobs:
           name: aws-distro-opentelemetry-dotnet-instrumentation-linux-x64-musl
           path: bin/aws-distro-opentelemetry-dotnet-instrumentation-linux-musl-x64.zip
   
-  build-arm-musl:
-    runs-on: codebuild-adot-dotnet-runner-${{ github.run_id }}-${{ github.run_attempt }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4.1.2
-        with:
-          fetch-depth: 0
+  # build-arm-musl:
+  #   runs-on: codebuild-adot-dotnet-runner-${{ github.run_id }}-${{ github.run_attempt }}
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4.1.2
+  #       with:
+  #         fetch-depth: 0
 
-      - name: Build in Docker container
-        run: |
-          set -e
-          docker build -t mybuildimage -f "./docker/alpine.dockerfile" ./docker
-          docker run --rm --mount type=bind,source="${GITHUB_WORKSPACE}",target=/project mybuildimage \
-            /bin/sh -c 'git config --global --add safe.directory /project && dotnet test && ./build.sh'
+  #     - name: Build in Docker container
+  #       run: |
+  #         set -e
+  #         docker build -t mybuildimage -f "./docker/alpine.dockerfile" ./docker
+  #         docker run --rm --mount type=bind,source="${GITHUB_WORKSPACE}",target=/project mybuildimage \
+  #           /bin/sh -c 'git config --global --add safe.directory /project && dotnet test && ./build.sh'
 
-      - name: Upload Artifact on MUSL ARM Linux
-        uses: actions/upload-artifact@v3
-        with:
-          name: aws-distro-opentelemetry-dotnet-instrumentation-linux-arm64-musl
-          path: bin/aws-distro-opentelemetry-dotnet-instrumentation-linux-musl-arm64.zip
+  #     - name: Upload Artifact on MUSL ARM Linux
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: aws-distro-opentelemetry-dotnet-instrumentation-linux-arm64-musl
+  #         path: bin/aws-distro-opentelemetry-dotnet-instrumentation-linux-musl-arm64.zip
           
-  dotnet-e2e-ec2-default-test:
-    needs: [build]
-    strategy:
-      fail-fast: false
-      matrix:
-        aws-region: [ 'us-east-1' ]
-    uses: ./.github/workflows/application-signals-dotnet-e2e-ec2-default-test.yml
-    secrets: inherit
-    with:
-      aws-region: ${{ matrix.aws-region }}
-      caller-workflow-name: 'main-build'
-      staging_wheel_name: 'aws-distro-opentelemetry-dotnet-instrumentation-linux-glibc-x64.zip'  
+  # dotnet-e2e-ec2-default-test:
+  #   needs: [build]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       aws-region: [ 'us-east-1' ]
+  #   uses: ./.github/workflows/application-signals-dotnet-e2e-ec2-default-test.yml
+  #   secrets: inherit
+  #   with:
+  #     aws-region: ${{ matrix.aws-region }}
+  #     caller-workflow-name: 'main-build'
+  #     staging_wheel_name: 'aws-distro-opentelemetry-dotnet-instrumentation-linux-glibc-x64.zip'  
       
-  dotnet-e2e-ec2-asg-test:
-    needs: [build]
-    strategy:
-      fail-fast: false
-      matrix:
-        aws-region: [ 'us-east-1' ]
-    uses: ./.github/workflows/application-signals-dotnet-e2e-ec2-asg-test.yml
-    secrets: inherit
-    with:
-      aws-region: ${{ matrix.aws-region }}
-      caller-workflow-name: 'main-build'
-      staging_wheel_name: 'aws-distro-opentelemetry-dotnet-instrumentation-linux-glibc-x64.zip'
+  # dotnet-e2e-ec2-asg-test:
+  #   needs: [build]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       aws-region: [ 'us-east-1' ]
+  #   uses: ./.github/workflows/application-signals-dotnet-e2e-ec2-asg-test.yml
+  #   secrets: inherit
+  #   with:
+  #     aws-region: ${{ matrix.aws-region }}
+  #     caller-workflow-name: 'main-build'
+  #     staging_wheel_name: 'aws-distro-opentelemetry-dotnet-instrumentation-linux-glibc-x64.zip'
     
 
-  release:
-    if: startsWith(github.ref, 'refs/heads/main')
-    needs: [build, build-arm, build-x64-musl, build-arm-musl, dotnet-e2e-ec2-default-test]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
+  # release:
+  #   if: startsWith(github.ref, 'refs/heads/main')
+  #   needs: [build, build-arm, build-x64-musl, build-arm-musl, dotnet-e2e-ec2-default-test]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Download Linux x64 Artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: aws-distro-opentelemetry-dotnet-instrumentation-linux-glibc-x64.zip
-          path: ./artifacts/linux/x64
+  #     - name: Download Linux x64 Artifact
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: aws-distro-opentelemetry-dotnet-instrumentation-linux-glibc-x64.zip
+  #         path: ./artifacts/linux/x64
 
-      - name: Download Windows Artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: aws-distro-opentelemetry-dotnet-instrumentation-windows
-          path: ./artifacts/windows
+  #     - name: Download Windows Artifact
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: aws-distro-opentelemetry-dotnet-instrumentation-windows
+  #         path: ./artifacts/windows
 
-      - name: Download macOS Artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: aws-distro-opentelemetry-dotnet-instrumentation-macOS
-          path: ./artifacts/macOS
+  #     - name: Download macOS Artifact
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: aws-distro-opentelemetry-dotnet-instrumentation-macOS
+  #         path: ./artifacts/macOS
 
 
-      - name: Download Linux ARM Artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: aws-distro-opentelemetry-dotnet-instrumentation-linux-arm64
-          path: ./artifacts/linux/arm64
+  #     - name: Download Linux ARM Artifact
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: aws-distro-opentelemetry-dotnet-instrumentation-linux-arm64
+  #         path: ./artifacts/linux/arm64
 
-      - name: Download Linux ARM MUSL Artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: aws-distro-opentelemetry-dotnet-instrumentation-linux-arm64-musl
-          path: ./artifacts/linux/arm64-musl
+  #     - name: Download Linux ARM MUSL Artifact
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: aws-distro-opentelemetry-dotnet-instrumentation-linux-arm64-musl
+  #         path: ./artifacts/linux/arm64-musl
 
-      - name: Download Linux X64 MUSL Artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: aws-distro-opentelemetry-dotnet-instrumentation-linux-x64-musl
-          path: ./artifacts/linux/x64-musl
+  #     - name: Download Linux X64 MUSL Artifact
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: aws-distro-opentelemetry-dotnet-instrumentation-linux-x64-musl
+  #         path: ./artifacts/linux/x64-musl
 
-      - name: Get Commit ID
-        id: get_commit
-        run: |
-          short_commit_id=$(echo ${GITHUB_SHA} | cut -c1-7)
-          echo "::set-output name=commit_id::${short_commit_id}"
+  #     - name: Get Commit ID
+  #       id: get_commit
+  #       run: |
+  #         short_commit_id=$(echo ${GITHUB_SHA} | cut -c1-7)
+  #         echo "::set-output name=commit_id::${short_commit_id}"
 
-      - name: Create GH release
-        id: create_release
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gh release create main-build-${{steps.get_commit.outputs.commit_id}}-pre-release \
-            --target "$GITHUB_REF_NAME" \
-            --title "Main Build Pre-Release Commit ${{ steps.get_commit.outputs.commit_id }}" \
-            --notes "Release and Pre-Release from Main build"
+  #     - name: Create GH release
+  #       id: create_release
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       run: |
+  #         gh release create main-build-${{steps.get_commit.outputs.commit_id}}-pre-release \
+  #           --target "$GITHUB_REF_NAME" \
+  #           --title "Main Build Pre-Release Commit ${{ steps.get_commit.outputs.commit_id }}" \
+  #           --notes "Release and Pre-Release from Main build"
 
-      - name: Upload Linux x64 Artifact to Release
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gh release upload "main-build-${{steps.get_commit.outputs.commit_id}}-pre-release" \
-            ./artifacts/linux/x64/*.zip \
-            --clobber
+  #     - name: Upload Linux x64 Artifact to Release
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       run: |
+  #         gh release upload "main-build-${{steps.get_commit.outputs.commit_id}}-pre-release" \
+  #           ./artifacts/linux/x64/*.zip \
+  #           --clobber
 
-      - name: Upload Windows Artifact to Release
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gh release upload "main-build-${{steps.get_commit.outputs.commit_id}}-pre-release" \
-            ./artifacts/windows/*.zip \
-            --clobber
+  #     - name: Upload Windows Artifact to Release
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       run: |
+  #         gh release upload "main-build-${{steps.get_commit.outputs.commit_id}}-pre-release" \
+  #           ./artifacts/windows/*.zip \
+  #           --clobber
 
-      - name: Upload macOS Artifact to Release
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gh release upload "main-build-${{steps.get_commit.outputs.commit_id}}-pre-release" \
-            ./artifacts/macOS/*.zip \
-            --clobber
+  #     - name: Upload macOS Artifact to Release
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       run: |
+  #         gh release upload "main-build-${{steps.get_commit.outputs.commit_id}}-pre-release" \
+  #           ./artifacts/macOS/*.zip \
+  #           --clobber
 
-      - name: Upload Linux ARM Artifact to Release
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gh release upload "main-build-${{steps.get_commit.outputs.commit_id}}-pre-release" \
-            ./artifacts/linux/arm64/*.zip \
-            --clobber
+  #     - name: Upload Linux ARM Artifact to Release
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       run: |
+  #         gh release upload "main-build-${{steps.get_commit.outputs.commit_id}}-pre-release" \
+  #           ./artifacts/linux/arm64/*.zip \
+  #           --clobber
 
-      - name: Upload Linux ARM MUSL Artifact to Release
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gh release upload "main-build-${{steps.get_commit.outputs.commit_id}}-pre-release" \
-            ./artifacts/linux/arm64-musl/*.zip \
-            --clobber
+  #     - name: Upload Linux ARM MUSL Artifact to Release
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       run: |
+  #         gh release upload "main-build-${{steps.get_commit.outputs.commit_id}}-pre-release" \
+  #           ./artifacts/linux/arm64-musl/*.zip \
+  #           --clobber
 
-      - name: Upload Linux X64 MUSL Artifact to Release
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gh release upload "main-build-${{steps.get_commit.outputs.commit_id}}-pre-release" \
-            ./artifacts/linux/x64-musl/*.zip \
-            --clobber
+  #     - name: Upload Linux X64 MUSL Artifact to Release
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       run: |
+  #         gh release upload "main-build-${{steps.get_commit.outputs.commit_id}}-pre-release" \
+  #           ./artifacts/linux/x64-musl/*.zip \
+  #           --clobber
